Translating Configuring CA Certificates
gatsbyjs/gatsby-es pull request #228
Opened 2020-05-26 02:23 UTC by palehox

Adding translation for `configuring-ca-certificates.md`

2020-05-27 13:55 UTC, Darking360 requested changes
Hola @palehox muchisimas gracias por el PR. Solo un par de cambios con ciertas palabras o conectores pero nada grave, al agregarlos podemos hacerle merge al PR :100:

2020-05-27 13:55 UTC, Darking360 commented on docs/docs/configuring-ca-certificates.md
> +Para verificar el valor de la ruta del certificado en la clave `cafile`, usa el siguiente comando para obtener todas las claves que se encuentran en tu configuración npm:
```suggestion
Para verificar el valor de la ruta del certificado en la clave `cafile`, usa el siguiente comando para obtener todas las claves que se encuentran en tu configuración de npm:
```

2020-05-27 13:55 UTC, Darking360 commented on docs/docs/configuring-ca-certificates.md
> +Ahora puedes verificar los valores en tu configuración yarn con el siguiente comando:
```suggestion
Ahora puedes verificar los valores en tu configuración de yarn con el siguiente comando:
```

2020-05-27 17:04 UTC, palehox commented
Hola @Darking360 ya realicé los cambios que me pediste, muchas gracias por el feedback.

2020-05-29 16:25 UTC, Darking360 approved these changes
Hey @palehox genial! Bienvenido entonces tu PR y tu a la comunidad de traductores :rocket: Muchas gracias :100:

2020-05-29 16:25 UTC, merged